server:
  port: 8810

spring:
  cloud:
    gateway:
      routes:
      - id: Rates_By_Date_And_Currencies
        uri: http://localhost:7770
        predicates:
        - Path=/Exchange_Rates_By_Date_And_Currencies/**
        - Query=date,
        - Query=currencyList
        filters:
        - RewritePath=/Exchange_Rates_By_Date_And_Currencies, /Rates_By_Date_And_Currencies
      - id: Rate
        uri: http://localhost:7770
        predicates:
        - Path=/Exchange_Rate/**
        - Query=date,
        - Query=currency,
        - Query=base
        filters:
        - RewritePath=/Exchange_Rate, /Rate
      - id: Rates_For_Year
        uri: http://localhost:7770
        predicates:
        - Path=/Exchange_Rates_For_Year/{currency}
        filters:
        - SetPath=/Rates_For_Year/{currency}
      - id: Rate_By_Date_And_Currency
        uri: http://localhost:7770
        predicates:
        - Path=/Exchange_Rate_By_Date_And_Currency/**
        - Query=date,
        - Query=currency,
        filters:
        - RewritePath=/Exchange_Rate_By_Date_And_Currency, /Rate_By_Date_And_Currency
      - id: Rate_By_Date
        uri: http://localhost:7770
        predicates:
        - Path=/Exchange_Rate_By_Date/**
        - Query=date
        filters:
        - RewritePath=/Exchange_Rate_By_Date, /Rate_By_Date
         
        
   